name: Docker Image CI

on:
  push:
    branches: [ 1.0 ] # Trigger on pushes to the 'main' branch

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: jcue/koth-ban-bot:latest
        # You can add more tags here, e.g.:
        # tags: |
        #   yourdockerhubusername/your-repo-name:latest
        #   yourdockerhubusername/your-repo-name:${{ github.sha }} # Tag with commit SHA
        #   yourdockerhubusername/your-repo-name:${{ github.run_number }} # Tag with run number
        # file: ./path/to/your/Dockerfile # If your Dockerfile is not at the root
